__default__:
  time: "0-01:00:00"
  partition: "batch"
  qos: "normal"
  nodes: 1
  n: 1
  explicit: ""
  job-name: "busi_madness.{rule}"

# taxonomy
kraken2:
  time: "00-01:00:00"
  partition: "gpu"

struo2_kraken2:
  time: "00-01:00:00"
  partition: "gpu"
  
